product-name: p-rabbitmq
network-properties:
  network:
    name: ((network_name))
  service_network:
    name: ((service_network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-properties:
  .on-demand-broker.canaries:
    value: ((on-demand-broker_canaries))
  .on-demand-broker.global_service_instance_quota:
    value: ((on-demand-broker_global_service_instance_quota))
  .on-demand-broker.max_in_flight:
    value: ((on-demand-broker_max_in_flight))
  .properties.enable_inter_node_tls:
    value: ((enable_inter_node_tls))
  .properties.enable_tls_selector:
    value: disabled
  .properties.global_settings_log_cache_compatibility:
    value: ((global_settings_log_cache_compatibility))
  .properties.global_settings_oauth:
    value: disabled
  .properties.global_settings_secure_bindings:
    value: "No"
  .properties.global_settings_shareable_instances:
    value: "No"
  .properties.metrics_polling_interval:
    value: ((metrics_polling_interval))
  .properties.multitenant_support:
    value: disabled
  .properties.on_demand_broker_plan_collection:
    value:
    - audit_logger_consume_delay: ((on_demand_broker_plan_collection_0_audit_logger_consume_delay))
      audit_logger_enabled: ((on_demand_broker_plan_collection_0_audit_logger_enabled))
      audit_logger_format: ((on_demand_broker_plan_collection_0_audit_logger_format))
      audit_logger_reconnect_time: ((on_demand_broker_plan_collection_0_audit_logger_reconnect_time))
      az_placement: ((on_demand_broker_plan_collection_0_az_placement))
      cf_service_access: ((on_demand_broker_plan_collection_0_cf_service_access))
      check_queue_sync: ((on_demand_broker_plan_collection_0_check_queue_sync))
      configured_plan_id: ((on_demand_broker_plan_collection_0_configured_plan_id))
      description: ((on_demand_broker_plan_collection_0_description))
      disk_limit_acknowledgement: ((on_demand_broker_plan_collection_0_disk_limit_acknowledgement))
      features: ((on_demand_broker_plan_collection_0_features))
      instance_quota: ((on_demand_broker_plan_collection_0_instance_quota))
      name: ((on_demand_broker_plan_collection_0_name))
      override_advanced_config: ((on_demand_broker_plan_collection_0_override_advanced_config))
      override_config: ((on_demand_broker_plan_collection_0_override_config))
      paid: ((on_demand_broker_plan_collection_0_paid))
      plan_vm_extensions: ((on_demand_broker_plan_collection_0_plan_vm_extensions))
      rabbitmq_cluster_partition_handling_strategy: ((on_demand_broker_plan_collection_0_rabbitmq_cluster_partition_handling_strategy))
      rabbitmq_number_of_nodes: ((on_demand_broker_plan_collection_0_rabbitmq_number_of_nodes))
      rabbitmq_persistent_disk_type: ((on_demand_broker_plan_collection_0_rabbitmq_persistent_disk_type))
      rabbitmq_vm_type: ((on_demand_broker_plan_collection_0_rabbitmq_vm_type))
      service_gateway_enabled: ((on_demand_broker_plan_collection_0_service_gateway_enabled))
      standby_replication_disk_limit: ((on_demand_broker_plan_collection_0_standby_replication_disk_limit))
      standby_replication_mode: ((on_demand_broker_plan_collection_0_standby_replication_mode))
      standby_replication_retention_time: ((on_demand_broker_plan_collection_0_standby_replication_retention_time))
  .properties.on_demand_tls_versions:
    value:
    - tlsv1.3
    - tlsv1.2
resource-config:
  on-demand-broker:
    instance_type:
      id: ((resource-var-on-demand-broker_instance_type))
    instances: ((resource-var-on-demand-broker_instances))
    persistent_disk:
      size_mb: ((resource-var-on-demand-broker_persistent_disk_size))
    max_in_flight: ((resource-var-on-demand-broker_max_in_flight))
  rabbitmq-broker:
    instance_type:
      id: ((resource-var-rabbitmq-broker_instance_type))
    instances: ((resource-var-rabbitmq-broker_instances))
    max_in_flight: ((resource-var-rabbitmq-broker_max_in_flight))
  rabbitmq-haproxy:
    instance_type:
      id: ((resource-var-rabbitmq-haproxy_instance_type))
    instances: ((resource-var-rabbitmq-haproxy_instances))
    max_in_flight: ((resource-var-rabbitmq-haproxy_max_in_flight))
  rabbitmq-server:
    instance_type:
      id: ((resource-var-rabbitmq-server_instance_type))
    instances: ((resource-var-rabbitmq-server_instances))
    persistent_disk:
      size_mb: ((resource-var-rabbitmq-server_persistent_disk_size))
    max_in_flight: ((resource-var-rabbitmq-server_max_in_flight))
syslog-properties:
  enabled: ((syslog_enabled))
  address: ((syslog_address))
  port: ((syslog_port))
  transport_protocol: ((syslog_transport_protocol))
  tls_enabled: ((syslog_tls_enabled))
  permitted_peer: ((syslog_permitted_peer))
  ssl_ca_certificate: ((syslog_ssl_ca_certificate))
  queue_size: ((syslog_queue_size))
  forward_debug_logs: ((syslog_forward_debug_logs))
  custom_rsyslog_configuration: ((syslog_custom_rsyslog_configuration))
errand-config:
  broker-deregistrar:
    pre-delete-state: ((broker-deregistrar_pre_delete_state))
  broker-registrar:
    post-deploy-state: ((broker-registrar_post_deploy_state))
  delete-all-service-instances:
    pre-delete-state: ((delete-all-service-instances_pre_delete_state))
  deregister-broker:
    pre-delete-state: ((deregister-broker_pre_delete_state))
  on-demand-broker-smoke-tests:
    post-deploy-state: ((on-demand-broker-smoke-tests_post_deploy_state))
  recreate-all-service-instances:
    post-deploy-state: ((recreate-all-service-instances_post_deploy_state))
  register-broker:
    post-deploy-state: ((register-broker_post_deploy_state))
  smoke-tests:
    post-deploy-state: ((smoke-tests_post_deploy_state))
  upgrade-all-service-instances:
    post-deploy-state: ((upgrade-all-service-instances_post_deploy_state))
