- type: replace
  path: /product-properties/.properties.uaa_internal_users_password_policies?
  value:
    value: configure_custom
    selected_option: configure_custom
- type: replace
  path: /product-properties/.properties.uaa_internal_users_password_policies.configure_custom.min_password_length?
  value:
    value: ((uaa_internal_users_password_policies_configure_custom_min_password_length))
- type: replace
  path: /product-properties/.properties.uaa_internal_users_password_policies.configure_custom.require_lowercase_char?
  value:
    value: ((uaa_internal_users_password_policies_configure_custom_require_lowercase_char))
- type: replace
  path: /product-properties/.properties.uaa_internal_users_password_policies.configure_custom.require_uppercase_char?
  value:
    value: ((uaa_internal_users_password_policies_configure_custom_require_uppercase_char))
- type: replace
  path: /product-properties/.properties.uaa_internal_users_password_policies.configure_custom.require_numeric_char?
  value:
    value: ((uaa_internal_users_password_policies_configure_custom_require_numeric_char))
- type: replace
  path: /product-properties/.properties.uaa_internal_users_password_policies.configure_custom.require_special_char?
  value:
    value: ((uaa_internal_users_password_policies_configure_custom_require_special_char))
- type: replace
  path: /product-properties/.properties.uaa_internal_users_password_policies.configure_custom.max_password_attempts?
  value:
    value: ((uaa_internal_users_password_policies_configure_custom_max_password_attempts))
