product-name: p-antivirus
network-properties: null
product-properties:
  .properties.action:
    value: notify
  .properties.cpu_limit:
    value: ((cpu_limit))
  .properties.daily_db_check_frequency:
    value: ((daily_db_check_frequency))
  .properties.database_connect_timeout:
    value: ((database_connect_timeout))
  .properties.database_mirrors:
    value: private_mirror
  .properties.database_mirrors.private_mirror.mirror_urls:
    value: ((database_mirrors_private_mirror_mirror_urls))
  .properties.enforce_cpu_limit:
    value: disabled
  .properties.exclude_paths:
    value: ((exclude_paths))
  .properties.memory_limit:
    value: ((memory_limit))
  .properties.on_access:
    value: ((on_access))
  .properties.scan_on_start:
    value: ((scan_on_start))
  .properties.schedule_interval:
    value: daily
  .properties.schedule_interval.daily.first_scheduled_scan_time:
    value: ((schedule_interval_daily_first_scheduled_scan_time))
  .properties.schedule_interval.daily.last_scheduled_scan_time:
    value: ((schedule_interval_daily_last_scheduled_scan_time))
  .properties.use_proxy:
    value: disabled
syslog-properties:
  enabled: ((syslog_enabled))
  address: ((syslog_address))
  port: ((syslog_port))
  transport_protocol: ((syslog_transport_protocol))
  tls_enabled: ((syslog_tls_enabled))
  permitted_peer: ((syslog_permitted_peer))
  ssl_ca_certificate: ((syslog_ssl_ca_certificate))
  queue_size: ((syslog_queue_size))
  forward_debug_logs: ((syslog_forward_debug_logs))
  custom_rsyslog_configuration: ((syslog_custom_rsyslog_configuration))
