- type: replace
  path: /product-properties/.properties.scrape_configs?
  value:
    value:
    - ca: ((scrape_configs_0_ca))
      insecure_skip_verify: ((scrape_configs_0_insecure_skip_verify))
      scrape_job: ((scrape_configs_0_scrape_job))
      server_name: ((scrape_configs_0_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_0_certificate))
        private_key_pem: ((scrape_configs_0_privatekey))
    - ca: ((scrape_configs_1_ca))
      insecure_skip_verify: ((scrape_configs_1_insecure_skip_verify))
      scrape_job: ((scrape_configs_1_scrape_job))
      server_name: ((scrape_configs_1_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_1_certificate))
        private_key_pem: ((scrape_configs_1_privatekey))
