- type: replace
  path: /product-properties/.properties.scrape_configs?
  value:
    value:
    - ca: ((scrape_configs_0_ca))
      insecure_skip_verify: ((scrape_configs_0_insecure_skip_verify))
      scrape_job: ((scrape_configs_0_scrape_job))
      server_name: ((scrape_configs_0_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_0_certificate))
        private_key_pem: ((scrape_configs_0_privatekey))
    - ca: ((scrape_configs_1_ca))
      insecure_skip_verify: ((scrape_configs_1_insecure_skip_verify))
      scrape_job: ((scrape_configs_1_scrape_job))
      server_name: ((scrape_configs_1_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_1_certificate))
        private_key_pem: ((scrape_configs_1_privatekey))
    - ca: ((scrape_configs_2_ca))
      insecure_skip_verify: ((scrape_configs_2_insecure_skip_verify))
      scrape_job: ((scrape_configs_2_scrape_job))
      server_name: ((scrape_configs_2_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_2_certificate))
        private_key_pem: ((scrape_configs_2_privatekey))
    - ca: ((scrape_configs_3_ca))
      insecure_skip_verify: ((scrape_configs_3_insecure_skip_verify))
      scrape_job: ((scrape_configs_3_scrape_job))
      server_name: ((scrape_configs_3_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_3_certificate))
        private_key_pem: ((scrape_configs_3_privatekey))
    - ca: ((scrape_configs_4_ca))
      insecure_skip_verify: ((scrape_configs_4_insecure_skip_verify))
      scrape_job: ((scrape_configs_4_scrape_job))
      server_name: ((scrape_configs_4_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_4_certificate))
        private_key_pem: ((scrape_configs_4_privatekey))
    - ca: ((scrape_configs_5_ca))
      insecure_skip_verify: ((scrape_configs_5_insecure_skip_verify))
      scrape_job: ((scrape_configs_5_scrape_job))
      server_name: ((scrape_configs_5_server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_5_certificate))
        private_key_pem: ((scrape_configs_5_privatekey))
