install_nr_dotnetcore_extension_jammy: true
install_nr_dotnetcore_extension_jammy_cached: true
install_nr_hwc_extension_windows: true
install_nr_hwc_extension_windows_cached: true
nr_dotnetcore_extension_jammy_cflinuxfs3_buildpack_order: 31
nr_dotnetcore_extension_jammy_cflinuxfs3_cached_buildpack_order: 32
nr_dotnetcore_extension_jammy_cflinuxfs4_buildpack_order: 31
nr_dotnetcore_extension_jammy_cflinuxfs4_cached_buildpack_order: 32
nr_hwc_extension_windows_buildpack_order: 33
nr_hwc_extension_windows_cached_buildpack_order: 34
delete-all_pre_delete_state: default
deploy-all_post_deploy_state: default
resource-var-delete-all_instance_type: automatic
resource-var-delete-all_max_in_flight: default
resource-var-deploy-all_instance_type: automatic
resource-var-deploy-all_max_in_flight: default
