cpu_limit: 50
daily_db_check_frequency: 12
database_connect_timeout: 30
exclude_paths: /proc/,/sys/
memory_limit: 4294967296
on_access: false
scan_on_start: false
schedule_interval_daily_first_scheduled_scan_time: '"00:00"'
schedule_interval_daily_last_scheduled_scan_time: '"23:59"'
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
