enable_inter_node_tls: false
global_settings_log_cache_compatibility: true
metrics_polling_interval: 30
on-demand-broker_canaries: 1
on-demand-broker_global_service_instance_quota: 20
on-demand-broker_max_in_flight: 3
on_demand_broker_plan_collection_0_audit_logger_consume_delay: 2
on_demand_broker_plan_collection_0_audit_logger_enabled: false
on_demand_broker_plan_collection_0_audit_logger_format: json
on_demand_broker_plan_collection_0_audit_logger_reconnect_time: 5
on_demand_broker_plan_collection_0_cf_service_access: enable
on_demand_broker_plan_collection_0_check_queue_sync: false
on_demand_broker_plan_collection_0_description: This plan provides a RabbitMQ instance
on_demand_broker_plan_collection_0_disk_limit_acknowledgement: non-existant-value
on_demand_broker_plan_collection_0_features: RabbitMQ
on_demand_broker_plan_collection_0_instance_quota: 10
on_demand_broker_plan_collection_0_name: on-demand-plan
on_demand_broker_plan_collection_0_paid: false
on_demand_broker_plan_collection_0_rabbitmq_cluster_partition_handling_strategy: pause_minority
on_demand_broker_plan_collection_0_rabbitmq_number_of_nodes: 3
on_demand_broker_plan_collection_0_service_gateway_enabled: false
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
broker-deregistrar_pre_delete_state: default
broker-registrar_post_deploy_state: default
delete-all-service-instances_pre_delete_state: default
deregister-broker_pre_delete_state: default
on-demand-broker-smoke-tests_post_deploy_state: default
recreate-all-service-instances_post_deploy_state: default
register-broker_post_deploy_state: default
smoke-tests_post_deploy_state: default
upgrade-all-service-instances_post_deploy_state: default
resource-var-on-demand-broker_instance_type: automatic
resource-var-on-demand-broker_instances: automatic
resource-var-on-demand-broker_max_in_flight: default
resource-var-on-demand-broker_persistent_disk_size: automatic
resource-var-rabbitmq-broker_instance_type: automatic
resource-var-rabbitmq-broker_instances: automatic
resource-var-rabbitmq-broker_max_in_flight: default
resource-var-rabbitmq-haproxy_instance_type: automatic
resource-var-rabbitmq-haproxy_instances: automatic
resource-var-rabbitmq-haproxy_max_in_flight: default
resource-var-rabbitmq-server_instance_type: automatic
resource-var-rabbitmq-server_instances: automatic
resource-var-rabbitmq-server_max_in_flight: default
resource-var-rabbitmq-server_persistent_disk_size: automatic
