cf-redis-broker_redis_maxmemory: 512MB
cf-redis-broker_service_instance_limit: 5
metrics_polling_interval: 30
redis-on-demand-broker_enable_config_api: false
redis-on-demand-broker_maximum_parallel_upgrades: 1
redis-on-demand-broker_service_instance_limit: 20
redis-on-demand-broker_upgrade_canary_number: 1
service_gateway_ports_range: 1025-1100
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
broker-deregistrar_pre_delete_state: default
broker-registrar_post_deploy_state: default
delete-all-service-instances-and-deregister-broker_pre_delete_state: default
on-demand-broker-smoke-tests_post_deploy_state: default
orphan-deployments_post_deploy_state: default
recreate-all-service-instances_post_deploy_state: default
register-broker_post_deploy_state: default
smoke-tests_post_deploy_state: default
upgrade-all-service-instances_post_deploy_state: default
resource-var-cf-redis-broker_instance_type: automatic
resource-var-cf-redis-broker_max_in_flight: default
resource-var-cf-redis-broker_persistent_disk_size: automatic
resource-var-redis-on-demand-broker_instance_type: automatic
resource-var-redis-on-demand-broker_instances: automatic
resource-var-redis-on-demand-broker_max_in_flight: default
