audit_mode: false
opsmanager_insecure_skip_tls_verify: false
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
usage_service_insecure_skip_tls_verify: false
resource-var-telemetry-centralizer_instance_type: automatic
resource-var-telemetry-centralizer_max_in_flight: default
