add_tags: false
app_cache_invalidate_ttl: 0s
app_limits: 0
consumer_queue_size: 10000
enable_event_tracing: false
firehose_keep_alive: 25s
flush_interval: 5s
hec_batch_size: 100
hec_retries: 3
hec_workers: 8
ignore_missing_app: true
missing_app_cache_invalidate_ttl: 0s
nozzle_memory: 256M
org_space_cache_invalidate_ttl: 72h
scale_out_nozzle: 2
skip_ssl_validation_cf: false
skip_ssl_validation_splunk: false
splunk_index: main
splunk_logging_index: ""
status_monitor_interval: 0s
delete-all_pre_delete_state: default
deploy-all_post_deploy_state: default
resource-var-delete-all_instance_type: automatic
resource-var-delete-all_max_in_flight: default
resource-var-deploy-all_instance_type: automatic
resource-var-deploy-all_max_in_flight: default
