---
pivnet-api-token: ((pivnet_token))
pivnet-product-slug: elastic-runtime
# file-glob: "srt*.pivotal"
file-glob: "cf*.pivotal"
product-version: ((cf-version))
#product-version-regex: ^4\.0\..*$
stemcell-iaas: aws
stemcell-version: ((jammy-stemcell-version))   # specific stemcell version to download
stemcell-heavy: true    