---
pivnet-api-token: ((pivnet_token))
pivnet-product-slug: p-clamav-addon
file-glob: "p-antivirus-2.3.74.pivotal"
product-version: ((antivirus-version))
# stemcell-iaas: "aws"
# stemcell-version: ((xenial-stemcell-version))   # specific stemcell version to download
#stemcell-heavy: true    