---
pivnet-api-token: ((pivnet_token))
pivnet-product-slug: p-spring-cloud-services
product-version: ((scs-version))
stemcell-iaas: aws
file-glob: "*.pivotal"
stemcell-version: ((jammy-stemcell-version))   # specific stemcell version to download
# stemcell-heavy: true    