---
pivnet-api-token: ((pivnet_token))
pivnet-product-slug: splunk-nozzle
product-version: ((splunk-version))
stemcell-iaas: aws
file-glob: "*.pivotal"
stemcell-version: ((jammy-stemcell-version))   # specific stemcell version to download
stemcell-heavy: true    