- type: replace
  path: /product-properties/.properties.remote_write_configs?
  value:
    value:
    - batch_send_deadline: ((remote_write_configs_0_batch_send_deadline))
      bearer_token:
        secret: ((remote_write_configs_0_bearer_token))
      ca: ((remote_write_configs_0_ca))
      insecure_skip_verify: ((remote_write_configs_0_insecure_skip_verify))
      max_backoff: ((remote_write_configs_0_max_backoff))
      max_samples_per_send: ((remote_write_configs_0_max_samples_per_send))
      max_shards: ((remote_write_configs_0_max_shards))
      min_backoff: ((remote_write_configs_0_min_backoff))
      min_shards: ((remote_write_configs_0_min_shards))
      password:
        secret: ((remote_write_configs_0_password))
      proxy_url: ((remote_write_configs_0_proxy_url))
      queue_capacity: ((remote_write_configs_0_queue_capacity))
      remote_timeout: ((remote_write_configs_0_remote_timeout))
      server_name: ((remote_write_configs_0_server_name))
      tls_certificates:
        cert_pem: ((remote_write_configs_0_certificate))
        private_key_pem: ((remote_write_configs_0_privatekey))
      url: ((remote_write_configs_0_url))
      username: ((remote_write_configs_0_username))
