- type: replace
  path: /product-properties/.properties.remote_write_configs?
  value:
    value:
    - batch_send_deadline: ((remote_write_configs_0_batch_send_deadline))
      bearer_token:
        secret: ((remote_write_configs_0_bearer_token))
      ca: ((remote_write_configs_0_ca))
      insecure_skip_verify: ((remote_write_configs_0_insecure_skip_verify))
      max_backoff: ((remote_write_configs_0_max_backoff))
      max_samples_per_send: ((remote_write_configs_0_max_samples_per_send))
      max_shards: ((remote_write_configs_0_max_shards))
      min_backoff: ((remote_write_configs_0_min_backoff))
      min_shards: ((remote_write_configs_0_min_shards))
      password:
        secret: ((remote_write_configs_0_password))
      proxy_url: ((remote_write_configs_0_proxy_url))
      queue_capacity: ((remote_write_configs_0_queue_capacity))
      remote_timeout: ((remote_write_configs_0_remote_timeout))
      server_name: ((remote_write_configs_0_server_name))
      tls_certificates:
        cert_pem: ((remote_write_configs_0_certificate))
        private_key_pem: ((remote_write_configs_0_privatekey))
      url: ((remote_write_configs_0_url))
      username: ((remote_write_configs_0_username))
    - batch_send_deadline: ((remote_write_configs_1_batch_send_deadline))
      bearer_token:
        secret: ((remote_write_configs_1_bearer_token))
      ca: ((remote_write_configs_1_ca))
      insecure_skip_verify: ((remote_write_configs_1_insecure_skip_verify))
      max_backoff: ((remote_write_configs_1_max_backoff))
      max_samples_per_send: ((remote_write_configs_1_max_samples_per_send))
      max_shards: ((remote_write_configs_1_max_shards))
      min_backoff: ((remote_write_configs_1_min_backoff))
      min_shards: ((remote_write_configs_1_min_shards))
      password:
        secret: ((remote_write_configs_1_password))
      proxy_url: ((remote_write_configs_1_proxy_url))
      queue_capacity: ((remote_write_configs_1_queue_capacity))
      remote_timeout: ((remote_write_configs_1_remote_timeout))
      server_name: ((remote_write_configs_1_server_name))
      tls_certificates:
        cert_pem: ((remote_write_configs_1_certificate))
        private_key_pem: ((remote_write_configs_1_privatekey))
      url: ((remote_write_configs_1_url))
      username: ((remote_write_configs_1_username))
    - batch_send_deadline: ((remote_write_configs_2_batch_send_deadline))
      bearer_token:
        secret: ((remote_write_configs_2_bearer_token))
      ca: ((remote_write_configs_2_ca))
      insecure_skip_verify: ((remote_write_configs_2_insecure_skip_verify))
      max_backoff: ((remote_write_configs_2_max_backoff))
      max_samples_per_send: ((remote_write_configs_2_max_samples_per_send))
      max_shards: ((remote_write_configs_2_max_shards))
      min_backoff: ((remote_write_configs_2_min_backoff))
      min_shards: ((remote_write_configs_2_min_shards))
      password:
        secret: ((remote_write_configs_2_password))
      proxy_url: ((remote_write_configs_2_proxy_url))
      queue_capacity: ((remote_write_configs_2_queue_capacity))
      remote_timeout: ((remote_write_configs_2_remote_timeout))
      server_name: ((remote_write_configs_2_server_name))
      tls_certificates:
        cert_pem: ((remote_write_configs_2_certificate))
        private_key_pem: ((remote_write_configs_2_privatekey))
      url: ((remote_write_configs_2_url))
      username: ((remote_write_configs_2_username))
    - batch_send_deadline: ((remote_write_configs_3_batch_send_deadline))
      bearer_token:
        secret: ((remote_write_configs_3_bearer_token))
      ca: ((remote_write_configs_3_ca))
      insecure_skip_verify: ((remote_write_configs_3_insecure_skip_verify))
      max_backoff: ((remote_write_configs_3_max_backoff))
      max_samples_per_send: ((remote_write_configs_3_max_samples_per_send))
      max_shards: ((remote_write_configs_3_max_shards))
      min_backoff: ((remote_write_configs_3_min_backoff))
      min_shards: ((remote_write_configs_3_min_shards))
      password:
        secret: ((remote_write_configs_3_password))
      proxy_url: ((remote_write_configs_3_proxy_url))
      queue_capacity: ((remote_write_configs_3_queue_capacity))
      remote_timeout: ((remote_write_configs_3_remote_timeout))
      server_name: ((remote_write_configs_3_server_name))
      tls_certificates:
        cert_pem: ((remote_write_configs_3_certificate))
        private_key_pem: ((remote_write_configs_3_privatekey))
      url: ((remote_write_configs_3_url))
      username: ((remote_write_configs_3_username))
    - batch_send_deadline: ((remote_write_configs_4_batch_send_deadline))
      bearer_token:
        secret: ((remote_write_configs_4_bearer_token))
      ca: ((remote_write_configs_4_ca))
      insecure_skip_verify: ((remote_write_configs_4_insecure_skip_verify))
      max_backoff: ((remote_write_configs_4_max_backoff))
      max_samples_per_send: ((remote_write_configs_4_max_samples_per_send))
      max_shards: ((remote_write_configs_4_max_shards))
      min_backoff: ((remote_write_configs_4_min_backoff))
      min_shards: ((remote_write_configs_4_min_shards))
      password:
        secret: ((remote_write_configs_4_password))
      proxy_url: ((remote_write_configs_4_proxy_url))
      queue_capacity: ((remote_write_configs_4_queue_capacity))
      remote_timeout: ((remote_write_configs_4_remote_timeout))
      server_name: ((remote_write_configs_4_server_name))
      tls_certificates:
        cert_pem: ((remote_write_configs_4_certificate))
        private_key_pem: ((remote_write_configs_4_privatekey))
      url: ((remote_write_configs_4_url))
      username: ((remote_write_configs_4_username))
    - batch_send_deadline: ((remote_write_configs_5_batch_send_deadline))
      bearer_token:
        secret: ((remote_write_configs_5_bearer_token))
      ca: ((remote_write_configs_5_ca))
      insecure_skip_verify: ((remote_write_configs_5_insecure_skip_verify))
      max_backoff: ((remote_write_configs_5_max_backoff))
      max_samples_per_send: ((remote_write_configs_5_max_samples_per_send))
      max_shards: ((remote_write_configs_5_max_shards))
      min_backoff: ((remote_write_configs_5_min_backoff))
      min_shards: ((remote_write_configs_5_min_shards))
      password:
        secret: ((remote_write_configs_5_password))
      proxy_url: ((remote_write_configs_5_proxy_url))
      queue_capacity: ((remote_write_configs_5_queue_capacity))
      remote_timeout: ((remote_write_configs_5_remote_timeout))
      server_name: ((remote_write_configs_5_server_name))
      tls_certificates:
        cert_pem: ((remote_write_configs_5_certificate))
        private_key_pem: ((remote_write_configs_5_privatekey))
      url: ((remote_write_configs_5_url))
      username: ((remote_write_configs_5_username))
